companies_list = [
    ["MSFT", "Microsoft Corp"],
    ["AAPL", "Apple Inc."],
    ["NVDA", "Nvidia Corp"],
    ["AMZN", "Amazon.com Inc"],
    ["META", "Meta Platforms, Inc. Class A"],
    ["GOOGL", "Alphabet Inc. Class A"],
    ["GOOG", "Alphabet Inc. Class C"],
    ["BRK-B", "Berkshire Hathaway Class B"],
    ["LLY", "Eli Lilly & Co."],
    ["AVGO", "Broadcom Inc."],
    ["TSLA", "Tesla, Inc."],
    ["JPM", "Jpmorgan Chase & Co."],
    ["UNH", "Unitedhealth Group Incorporated"],
    ["V", "Visa Inc."],
    ["XOM", "Exxon Mobil Corporation"],
    ["JNJ", "Johnson & Johnson"],
    ["MA", "Mastercard Incorporated"],
    ["PG", "Procter & Gamble Company"],
    ["HD", "Home Depot, Inc."],
    ["COST", "Costco Wholesale Corp"],
    ["MRK", "Merck & Co., Inc."],
    ["ABBV", "Abbvie Inc."],
    ["CRM", "Salesforce, Inc."],
    ["ADBE", "Adobe Inc."],
    ["AMD", "Advanced Micro Devices"],
    ["CVX", "Chevron Corporation"],
    ["NFLX", "Netflix Inc"],
    ["WMT", "Walmart Inc."],
    ["PEP", "Pepsico, Inc."],
    ["KO", "Coca-Cola Company"],
    ["BAC", "Bank of America Corporation"],
    ["ACN", "Accenture Plc"],
    ["TMO", "Thermo Fisher Scientific, Inc."],
    ["MCD", "Mcdonald's Corporation"],
    ["LIN", "Linde Plc"],
    ["CSCO", "Cisco Systems, Inc."],
    ["DIS", "The Walt Disney Company"],
    ["ABT", "Abbott Laboratories"],
    ["INTC", "Intel Corp"],
    ["INTU", "Intuit Inc"],
    ["ORCL", "Oracle Corp"],
    ["WFC", "Wells Fargo & Co."],
    ["CMCSA", "Comcast Corp"],
    ["QCOM", "Qualcomm Inc"],
    ["IBM", "International Business Machines Corporation"],
    ["VZ", "Verizon Communications"],
    ["CAT", "Caterpillar Inc."],
    ["DHR", "Danaher Corporation"],
    ["NOW", "Servicenow, Inc."],
    ["AMGN", "Amgen Inc"],
    ["PFE", "Pfizer Inc."],
    ["AMAT", "Applied Materials Inc"],
    ["GE", "General Electric Company"],
    ["UNP", "Union Pacific Corp."],
    ["TXN", "Texas Instruments Incorporated"],
    ["UBER", "Uber Technologies, Inc."],
    ["PM", "Philip Morris International Inc."],
    ["SPGI", "S&p Global Inc."],
    ["ISRG", "Intuitive Surgical Inc."],
    ["LOW", "Lowe's Companies Inc."],
    ["BKNG", "Booking Holdings Inc."],
    ["COP", "Conocophillips"],
    ["NKE", "Nike, Inc."],
    ["RTX", "Rtx Corporation"],
    ["HON", "Honeywell International, Inc."],
    ["GS", "Goldman Sachs Group Inc."],
    ["AXP", "American Express Company"],
    ["PLD", "Prologis, Inc."],
    ["T", "At&t Inc."],
    ["LRCX", "Lam Research Corp"],
    ["BA", "Boeing Company"],
    ["ELV", "Elevance Health, Inc."],
    ["NEE", "Nextra Energy, Inc."],
    ["PANW", "Palo Alto Networks, Inc."],
    ["SYK", "Stryker Corporation"],
    ["MDT", "Medtronic Plc"],
    ["TJX", "Tjx Companies, Inc."],
    ["BLK", "Blackrock, Inc."],
    ["MS", "Morgan Stanley"],
    ["ETN", "Eaton Corporation, Plcs"],
    ["SBUX", "Starbucks Corp"],
    ["VRTX", "Vertex Pharmaceuticals Inc"],
    ["PGR", "Progressive Corporation"],
    ["UPS", "United Parcel Service, Inc. Class B"],
    ["DE", "Deere & Company"],
    ["C", "Citigroup Inc."],
    ["ADP", "Automatic Data Processing"],
    ["BMY", "Bristol-Myers Squibb Co."],
    ["REGN", "Regeneron Pharmaceuticals Inc"],
    ["CB", "Chubb Limited"],
    ["MDLZ", "Mondelez International, Inc. Class A"],
    ["CVS", "Cvs Health Corporation"],
    ["CI", "The Cigna Group"],
    ["MMC", "Marsh & Mclennan Companies, Inc."],
    ["ADI", "Analog Devices, Inc."],
    ["SCHW", "The Charles Schwab Corporation"],
    ["BSX", "Boston Scientific Corp."],
    ["LMT", "Lockheed Martin Corp."],
    ["MU", "Micron Technology, Inc."],
    ["GILD", "Gilead Sciences Inc"],
    ["BX", "Blackstone Inc."],
    ["ZTS", "Zoetis Inc."],
    ["AMT", "American Tower Corporation"],
    ["KLAC", "Kla Corporation"],
    ["FI", "Fiserv, Inc."],
    ["SNPS", "Synopsys Inc"],
    ["CDNS", "Cadence Design Systems"],
    ["TMUS", "T-Mobile Us, Inc."],
    ["EQIX", "Equinix, Inc. Reit"],
    ["ICE", "Intercontinental Exchange Inc."],
    ["SO", "The Southern Company"],
    ["CME", "Cme Group Inc."],
    ["SHW", "The Sherwin-Williams Company"],
    ["CSX", "Csx Corporation"],
    ["MO", "Altria Group, Inc."],
    ["CMG", "Chipotle Mexican Grill, Inc."],
    ["DUK", "Duke Energy Corporation"],
    ["BDX", "Becton, Dickinson and Co."],
    ["ANET", "Arista Networks"],
    ["ITW", "Illinois Tool Works Inc."],
    ["WM", "Waste Management, Inc."],
    ["TGT", "Target Corporation"],
    ["CL", "Colgate-Palmolive Company"],
    ["SLB", "Schlumberger Limited"],
    ["ABNB", "Airbnb, Inc. Class A"],
    ["PH", "Parker-Hannifin Corporation"],
    ["MCK", "Mckesson Corporation"],
    ["EOG", "Eog Resources, Inc."],
    ["PYPL", "Paypal Holdings, Inc."],
    ["MPC", "Marathon Petroleum Corporation"],
    ["NOC", "Northrop Grumman Corp."],
    ["USB", "U.S. Bancorp"],
    ["PSX", "Phillips 66"],
    ["MCO", "Moody's Corporation"],
    ["APH", "Amphenol Corporation"],
    ["TT", "Trane Technologies Plc"],
    ["AON", "Aon Plc Class A"],
    ["HCA", "Hca Healthcare, Inc."],
    ["MAR", "Marriot International Class A"],
    ["TDG", "Transdigm Group Incorporated"],
    ["NXPI", "Nxp Semiconductors N.v."],
    ["GD", "General Dynamics Corporation"],
    ["ORLY", "O'reilly Automotive, Inc."],
    ["EMR", "Emerson Electric Co."],
    ["PNC", "Pnc Financial Services Group"],
    ["ROP", "Roper Technologies, Inc."],
    ["NSC", "Norfolk Southern Corp."],
    ["FDX", "Fedex Corporation"],
    ["ADSK", "Autodesk Inc"],
    ["PCAR", "Paccar Inc"],
    ["FCX", "Freeport-Mcmoran Inc."],
    ["GM", "General Motors Company"],
    ["LULU", "Lululemon Athletica Inc."],
    ["PXD", "Pioneer Natural Resource Co."],
    ["MSI", "Motorola Solutions, Inc."],
    ["CTAS", "Cintas Corp"],
    ["EW", "Edwards Lifesciences Corp"],
    ["COF", "Capital One Financial"],
    ["MMM", "3m Company"],
    ["ECL", "Ecolab, Inc."],
    ["F", "Ford Motor Company"],
    ["AJG", "Arthur J. Gallagher & Co."],
    ["HLT", "Hilton Worldwide Holdings Inc."],
    ["APD", "Air Products & Chemicals, Inc."],
    ["ROST", "Ross Stores Inc"],
    ["TRV", "The Travelers Companies, Inc."],
    ["AIG", "American International Group, Inc."],
    ["VLO", "Valero Energy Corporation"],
    ["WELL", "Welltower Inc."],
    ["TFC", "Truist Financial Corporation"],
    ["AZO", "Autozone, Inc."],
    ["SPG", "Simon Property Group, Inc."],
    ["IDXX", "Idexx Laboratories Inc"],
    ["CARR", "Carrier Global Corporation"],
    ["CCI", "Crown Castle Inc."],
    ["MSCI", "Msci, Inc."],
    ["DXCM", "Dexcom, Inc."],
    ["NUE", "Nucor Corporation"],
    ["HUM", "Humana Inc."],
    ["MCHP", "Microchip Technology Inc"],
    ["URI", "United Rentals, Inc."],
    ["FTNT", "Fortinet, Inc."],
    ["DHI", "D.R. Horton Inc."],
    ["PSA", "Public Storage"],
    ["TEL", "Te Connectivity Ltd"],
    ["SRE", "Sempra"],
    ["CPRT", "Copart Inc"],
    ["O", "Realty Income Corporation"],
    ["DLR", "Digital Realty Trust, Inc."],
    ["BK", "Bank of New York Mellon Corporation"],
    ["MET", "Metlife, Inc."],
    ["WMB", "Williams Companies Inc."],
    ["GWW", "W.W. Grainger, Inc."],
    ["AFL", "Aflac Inc."],
    ["ALL", "The Allstate Corporation"],
    ["CNC", "Centene Corporation"],
    ["MNST", "Monster Beverage Corporation"],
    ["CEG", "Constellation Energy Corporation"],
    ["OKE", "Oneok, Inc."],
    ["AEP", "American Electric Power Company, Inc."],
    ['KMB', 'Kimberly-Clark Corp.'] ,
    ['SYY', 'Sysco Corporation'] ,
    ['AMP', 'Ameriprise Financial, Inc.'] ,
    ['FAST', 'Fastenal Co'] ,
    ['LHX', 'L3harris Technologies, Inc.'] ,
    ['STZ', 'Constellation Brands, Inc.'] ,
    ['IQV', 'Iqvia Holdings Inc.'] ,
    ['HES', 'Hess Corporation'] ,
    ['LEN', 'Lennar Corporation Class A'] ,
    ['PAYX', 'Paychex Inc'] ,
    ['AME', 'Ametek, Inc.'] ,
    ['CTVA', 'Corteva, Inc.'] ,
    ['NEM', 'Newmont Corporation'] ,
    ['A', 'Agilent Technologies Inc.'] ,
    ['PRU', 'Prudential Financial, Inc.'] ,
    ['DOW', 'Dow Inc.'] ,
    ['ODFL', 'Old Dominion Freight Line'] ,
    ['CTSH', 'Cognizant Technology Solutions'] ,
    ['COR', 'Cencora, Inc.'] ,
    ['OXY', 'Occidental Petroleum Corporation'] ,
    ['D', 'Dominion Energy, Inc'] ,
    ['JCI', 'Johnson Controls International Plc'] ,
    ['OTIS', 'Otis Worldwide Corporation'] ,
    ['FIS', 'Fidelity National Information Services, Inc.'] ,
    ['YUM', 'Yum! Brands, Inc.'] ,
    ['GIS', 'General Mills, Inc.'] ,
    ['CMI', 'Cummins Inc.'] ,
    ['GPN', 'Global Payments, Inc.'] ,
    ['VRSK', 'Verisk Analytics, Inc.'] ,
    ['BIIB', 'Biogen Inc.'] ,
    ['RSG', 'Republic Services Inc.'] ,
    ['IT', 'Gartner, Inc.'] ,
    ['MPWR', 'Monolithic Power Systems, Inc.'] ,
    ['ON', 'On Semiconductor Corp'] ,
    ['IR', 'Ingersoll Rand Inc.'] ,
    ['PCG', 'Pg&e Corporation'] ,
    ['EXC', 'Exelon Corporation'] ,
    ['EL', 'The Estee Lauder Companies Inc. Class A'] ,
    ['CSGP', 'Costar Group Inc'] ,
    ['EA', 'Electronic Arts Inc'] ,
    ['KVUE', 'Kenvue Inc.'] ,
    ['PPG', 'Ppg Industries, Inc.'] ,
    ['MLM', 'Martin Marietta Materials'] ,
    ['GEHC', 'Ge Healthcare Technologies Inc.'] ,
    ['KMI', 'Kinder Morgan, Inc.'] ,
    ['CDW', 'Cdw Corporation'] ,
    ['XEL', 'Xcel Energy, Inc.'] ,
    ['ROK', 'Rockwell Automation, Inc.'] ,
    ['FICO', 'Fair Isaac Corporation'] ,
    ['VMC', 'Vulcan Materials Company'] ,
    ['KDP', 'Keurig Dr Pepper Inc.'] ,
    ['EFX', 'Equifax, Incorporated'] ,
    ['HAL', 'Halliburton Company'] ,
    ['ACGL', 'Arch Capital Group Ltd'] ,
    ['PWR', 'Quanta Services, Inc.'] ,
    ['VICI', 'Vici Properties Inc.'] ,
    ['ED', 'Consolidated Edison, Inc.'] ,
    ['WST', 'West Pharmaceutical Services, Inc.'] ,
    ['EXR', 'Extra Space Storage, Inc.'] ,
    ['KR', 'The Kroger Co.'] ,
    ['CHTR', 'Charter Comm Inc Del Cl a'] ,
    ['DG', 'Dollar General Corp.'] ,
    ['DLTR', 'Dollar Tree Inc.'] ,
    ['FANG', 'Diamondback Energy, Inc.'] ,
    ['BKR', 'Baker Hughes Company'] ,
    ['PEG', 'Public Service Enterprise Group Incorporated'] ,
    ['XYL', 'Xylem Inc'] ,
    ['MRNA', 'Moderna, Inc.'] ,
    ['DD', 'Dupont De Nemours, Inc.'] ,
    ['ANSS', 'Ansys Inc'] ,
    ['FTV', 'Fortive Corporation'] ,
    ['HSY', 'The Hershey Company'] ,
    ['KHC', 'The Kraft Heinz Company'] ,
    ['ADM', 'Archer Daniels Midland Company'] ,
    ['KEYS', 'Keysight Technologies, Inc.'] ,
    ['WTW', 'Willis Towers Watson Public Limited Companys'] ,
    ['DFS', 'Discover Financial Services'] ,
    ['RCL', 'Royal Caribbean Group'] ,
    ['HIG', 'The Hartford Financial Services Group, Inc.'] ,
    ['DVN', 'Devon Energy Corporation'] ,
    ['CBRE', 'Cbre Group, Inc.'] ,
    ['RMD', 'Resmed Inc.'] ,
    ['ZBH', 'Zimmer Biomet Holdings, Inc.'] ,
    ['DAL', 'Delta Air Lines, Inc.'] ,
    ['ULTA', 'Ulta Beauty, Inc.'] ,
    ['MTD', 'Mettler-Toledo International'] ,
    ['CAH', 'Cardinal Health, Inc.'] ,
    ['TSCO', 'Tractor Supply Co'] ,
    ['EIX', 'Edison International'] ,
    ['HPQ', 'Hp Inc.'] ,
    ['GLW', 'Corning Incorporated'] ,
    ['WAB', 'Wabtec Inc.'] ,
    ['TROW', 'T Rowe Price Group Inc'] ,
    ['TTWO', 'Take-Two Interactive Software Inc'] ,
    ['LYB', 'Lyondellbasell Industries N.v. Class A'] ,
    ['WY', 'Weyerhaeuser Company'] ,
    ['WEC', 'Wec Energy Group, Inc.'] ,
    ['AVB', 'Avalonbay Communities, Inc.'] ,
    ['NVR', 'Nvr, Inc.'] ,
    ['CHD', 'Church & Dwight Co., Inc.'],
    ['AWK', 'American Water Works Company, Inc'],
    ['APTV', 'Aptiv Plc'],
    ['BR', 'Broadridge Financial Solutions Inc'],
    ['FITB', 'Fifth Third Bancorp'],
    ['SBAC', 'Sba Communications Corp'],
    ['BLDR', 'Builders Firstsource, Inc.'],
    ['HWM', 'Howmet Aerospace Inc.'],
    ['MOH', 'Molina Healthcare, Inc.'],
    ['PHM', 'Pultegroup, Inc.'],
    ['STT', 'State Street Corporation'],
    ['MTB', 'M&t Bank Corp.'],
    ['DOV', 'Dover Corporation'],
    ['EBAY', 'Ebay Inc'],
    ['STE', 'Steris Plc'],
    ['WBD', 'Warner Bros. Discovery, Inc. Series a'],
    ['ILMN', 'Illumina Inc'],
    ['RJF', 'Raymond James Financial, Inc.'],
    ['DTE', 'Dte Energy Company'],
    ['ALGN', 'Align Technology Inc'],
    ['PTC', 'Ptc, Inc'],
    ['ETR', 'Entergy Corporation'],
    ['IFF', 'International Flavors & Fragrances Inc.'],
    ['BAX', 'Baxter International Inc.'],
    ['GPC', 'Genuine Parts Company'],
    ['EQR', 'Equity Residential'],
    ['LVS', 'Las Vegas Sands Corp.'],
    ['TDY', 'Teledyne Technologies Incorporated'],
    ['IRM', 'Iron Mountain Inc.'],
    ['HPE', 'Hewlett Packard Enterprise Company'],
    ['DRI', 'Darden Restaurants, Inc.'],
    ['TRGP', 'Targa Resources Corp.'],
    ['FLT', 'Fleetcor Technologies, Inc.'],
    ['FE', 'Firstenergy Corp.'],
    ['LUV', 'Southwest Airlines Co.'],
    ['CBOE', 'Cboe Global Markets, Inc.'],
    ['ES', 'Eversource Energy'],
    ['PPL', 'Ppl Corporation'],
    ['AKAM', 'Akamai Technologies Inc'],
    ['LH', 'Laboratory Corporation of America Holdings'],
    ['HUBB', 'Hubbell Incorporated'],
    ['NDAQ', 'Nasdaq, Inc.'],
    ['BRO', 'Brown & Brown, Inc.'],
    ['CLX', 'Clorox Company'],
    ['BALL', 'Ball Corporation'],
    ['WAT', 'Waters Corp'],
    ['INVH', 'Invitation Homes Inc.'],
    ['GRMN', 'Garmin Ltd'],
    ['NTAP', 'Netapp, Inc'],
    ['STLD', 'Steel Dynamics Inc'],
    ['AXON', 'Axon Enterprise, Inc.'],
    ['COO', 'The Cooper Companies, Inc.'],
    ['CTRA', 'Coterra Energy Inc.'],
    ['ARE', 'Alexandria Real Estate Equities, Inc.'],
    ['EXPD', 'Expeditors International of Washington, Inc.'],
    ['WDC', 'Western Digital Corp.'],
    ['J', 'Jacobs Solutions Inc.'],
    ['VLTO', 'Veralto Corporation'],
    ['VTR', 'Ventas, Inc.'],
    ['HOLX', 'Hologic Inc'],
    ['HBAN', 'Huntington Bancshares Inc'],
    ['TYL', 'Tyler Technologies, Inc.'],
    ['JBL', 'Jabil Inc.'],
    ['AEE', 'Ameren Corporation'],
    ['FDS', 'Factset Research Systems'],
    ['EXPE', 'Expedia Group, Inc.'],
    ['JBHT', 'Jb Hunt Transport Services Inc'],
    ['ENPH', 'Enphase Energy, Inc.'],
    ['CNP', 'Centerpoint Energy, Inc.'],
    ['VRSN', 'Verisign Inc'],
    ['CINF', 'Cincinnati Financial Corp'],
    ['PFG', 'Principal Financial Group, Inc.'],
    ['STX', 'Seagate Technology Holdings Plcs'],
    ['RF', 'Regions Financial Corp.'],
    ['TXT', 'Textron, Inc.'],
    ['OMC', 'Omnicom Group Inc.'],
    ['IEX', 'Idex Corporation'],
    ['ATO', 'Atmos Energy Corporation'],
    ['SWKS', 'Skyworks Solutions Inc'],
    ['NTRS', 'Northern Trust Corp'],
    ['FSLR', 'First Solar, Inc.'],
    ['AVY', 'Avery Dennison Corp.'],
    ['EPAM', 'Epam Systems, Inc.'],
    ['CMS', 'Cms Energy Corporation'],
    ['MKC', 'Mccormick & Company, Incorporated Non-Vtg Cs'],
    ['MAS', 'Masco Corporation'],
    ['WRB', 'W.R. Berkley Corporation'],
    ['SYF', 'Synchrony Financial'],
    ['WBA', 'Walgreens Boots Alliance, Inc'],
    ['TER', 'Teradyne, Inc.'],
    ['LDOS', 'Leidos Holdings, Inc.'],
    ['CCL', 'Carnival Corporation'],
    ['EG', 'Everest Group, Ltd.'],
    ['POOL', 'Pool Corporation'],
    ['CE', 'Celanese Corporation'],
    ['PKG', 'Packaging Corp of America'],
    ['CF', 'Cf Industries Holding, Inc.'],
    ['CFG', 'Citizens Financial Group, Inc.'],
    ['TSN', 'Tyson Foods, Inc.'],
    ['DPZ', "Domino's Pizza Inc."],
    ['ESS', 'Essex Property Trust, Inc'],
    ['BBY', 'Best Buy Company, Inc.'],
    ['MAA', 'Mid-America Apartment Communities, Inc.'],
    ['LW', 'Lamb Weston Holdings, Inc.'],
    ['DGX', 'Quest Diagnostics Inc.'],
    ['K', 'Kellanova'],
    ['EQT', 'Eqt Corp'],
    ['VTRS', 'Viatris Inc.'],
    ['NDSN', 'Nordson Corp'],
    ['SNA', 'Snap-on Incorporated'],
    ['ALB', 'Albemarle Corporation'],
    ['UAL', 'United Airlines Holdings, Inc.'],
    ['SWK', 'Stanley Black & Decker, Inc.'],
    ['HST', 'Host Hotels & Resorts, Inc.'],
    ['TRMB', 'Trimble Inc.'],
    ['PODD', 'Insulet Corporation'],
    ['L', 'Loews Corporation'],
    ['ZBRA', 'Zebra Technologies Corporation'],
    ['SJM', 'The J.M. Smucker Company'],
    ['AMCR', 'Amcor Plcs'],
    ['MRO', 'Marathon Oil Corporation'],
    ['KEY', 'Keycorp'],
    ['CAG', 'Conagra Brands, Inc.'],
    ['LKQ', 'Lkq Corporation'],
    ['BG', 'Bunge Global Sa'],
    ['RVTY', 'Revvity, Inc.'],
    ['MGM', 'Mgm Resorts International'],
    ['JKHY', 'Henry [Jack] & Associates'],
    ['LYV', 'Live Nation Entertainment Inc.'],
    ['PNR', 'Pentair Plc'],
    ['GEN', 'Gen Digital Inc.'],
    ['IPG', 'The Interpublic Group of Companies, Inc.'],
    ['IP', 'International Paper Co.'],
    ['ROL', 'Rollins, Inc.'],
    ['LNT', 'Alliant Energy Corporation'],
    ['KMX', 'Carmax Inc.'],
    ['KIM', 'Kimco Realty Corp.'],
    ['TFX', 'Teleflex Incorporated'],
    ['JNPR', 'Juniper Networks Inc'],
    ['ALLE', 'Allegion Public Limited Company'],
    ['NRG', 'Nrg Energy, Inc.'],
    ['TAP', 'Molson Coors Beverage Company Class B'],
    ['CRL', 'Charles River Laboratories International, Inc.'],
    ['EVRG', 'Evergy, Inc.'],
    ['AES', 'Aes Corporation'],
    ['DAY', 'Dayforce, Inc.'],
    ['QRVO', 'Qorvo, Inc.'],
    ['FFIV', 'F5, Inc.'],
    ['TECH', 'Bio-Techne Corp.'],
    ['HII', 'Huntington Ingalls Industries, Inc.'],
    ['WRK', 'Westrock Company'],
    ['GL', 'Globe Life Inc.'],
    ['UDR', 'Udr, Inc.'],
    ['INCY', 'Incyte Genomics Inc'],
    ['BF-B', 'Brown-Forman Corporation Class B'],
    ['NI', 'Nisource Inc.'],
    ['CTLT', 'Catalent, Inc.'],
    ['BBWI', 'Bath & Body Works, Inc.'],
    ['WYNN', 'Wynn Resorts Ltd'],
    ['CPT', 'Camden Property Trust'],
    ['MTCH', 'Match Group, Inc'],
    ['UHS', 'Universal Health Services, Inc. Class B'],
    ['MOS', 'The Mosaic Company'],
    ['REG', 'Regency Centers Corporation'],
    ['AOS', 'A.O. Smith Corporation'],
    ['TPR', 'Tapestry, Inc.'],
    ['EMN', 'Eastman Chemical Company'],
    ['NWSA', 'News Corporation Class A'],
    ['HSIC', 'Henry Schein Inc'],
    ['AAL', 'American Airlines Group Inc.'],
    ['CZR', 'Caesars Entertainment, Inc.'],
    ['PEAK', 'Healthpeak Properties, Inc.'],
    ['ETSY', 'Etsy, Inc.'],
    ['APA', 'Apa Corporation'],
    ['PAYC', 'Paycom Software, Inc.'],
    ['BXP', 'Boston Properties, Inc.'],
    ['AIZ', 'Assurant, Inc.'],
    ['CHRW', 'C.H. Robinson Worldwide, Inc.'],
    ['RHI', 'Robert Half Inc.'],
    ['HRL', 'Hormel Foods Corporation'],
    ['MKTX', 'Marketaxess Holdings Inc.'],
    ['CPB', 'Campbell Soup Company'],
    ['GNRC', 'Generac Holdings Inc'],
    ['BEN', 'Franklin Resources, Inc.'],
    ['PNW', 'Pinnacle West Capital Corporation'],
    ['BWA', 'Borgwarner Inc.'],
    ['FOXA', 'Fox Corporation Class A'],
    ['FRT', 'Federal Realty Investment Trust'],
    ['IVZ', 'Invesco Ltd'],
    ['XRAY', 'Dentsply Sirona Inc.'],
    ['RL', 'Ralph Lauren Corporation'],
    ['CMA', 'Comerica Incorporated'],
    ['NCLH', 'Norwegian Cruise Line Holdings Ltd.s'],
    ['BIO', 'Bio-Rad Laboratories, Inc.Class A'],
    ['FMC', 'Fmc Corporation'],
    ['HAS', 'Hasbro, Inc.'],
    ['PARA', 'Paramount Global Class B'],
    ['DVA', 'Davita Inc.'],
    ['ZION', 'Zions Bancorporation N.a.'],
    ['WHR', 'Whirlpool Corp.'],
    ['MHK', 'Mohawk Industries, Inc.'],
    ['VFC', 'V.F. Corporation'],
    ['FOX', 'Fox Corporation Class B'],
    ['NWS', 'News Corporation Class B']
]




